### ISSUE TITLE
Error while accessing API at https://rozklad.org.ua

### ISSUE THREAD

**Issue by kingracer** [sochka/kpiexport2#2]
When trying to export schedule i'm getting error:
![image](https://cloud.githubusercontent.com/assets/8422318/17741290/4dc7976c-64a4-11e6-8dd9-3bcdcf384683.png)

**Comment by Wapweb** [comment]
@kingracer Hi. rozklad-api SSL is expired . I'll fix it in a few days

**Comment by Wapweb** [comment]
i renewed the ssl of rozklad api but kpiexport2 still not working.
![untitled](https://cloud.githubusercontent.com/assets/8421581/17866190/44a77d92-68ae-11e6-9688-8f632930bb3b.png)

**Comment by kingracer** [comment]
It's working for me now, thanks :)

Upd. It's partially working... Just some info puts into wrong places

**Comment by kingracer** [comment]
Idk why, but now it's fixed for me. Thank you :)

**Comment by sashasochka** [comment]
I will check out things soon if everything is correct and fix
