### ISSUE TITLE
Сдвиг расписания.

### ISSUE THREAD

**Issue by denquee** [sochka/kpiexport2#3]
Первая неделя началась с 13го, а в календаре началась с 6го, соответственно, произошел сдвиг на неделю.

**Comment by Dmitry-GH** [comment]
Подтверждаю проблему.

**Comment by sashasochka** [comment]
Це у всіх групах так, чи тільки на конкретних ваших? Я просто спеціально перевіряв на своїй в цьому семестрі і все було, ніби, ок. (Хоча я може щось наплутав, я вже не вчусь і міг переплутати перші і другі тижні)

**Comment by denquee** [comment]
Да, не только в нашей группе, проверил еще пару, начинаются так же с 6го числа.
