### ISSUE TITLE
Сдвиг расписания

### ISSUE THREAD

**Issue by wildOsprey** [sochka/kpiexport2#6]
Вместо расписания на первую неделю отображает расписание на вторую и наоборот.

**Comment by kerimovkhikmet** [comment]
Тоже самое((

**Comment by Andriy2** [comment]
+

**Comment by volmk** [comment]
Для исправления:

**Comment by volmk** [comment]
> Вместо расписания на первую неделю отображает расписание на вторую и наоборот.

Для исправления перейдите на сайт:
1. Нажмите F12
2. Сверху перейдите во вкладку Sources
3. Перейдите в папку top/kpiexport.azurwebsites.net/app
4. В файле app.components.js в строчке 66 замените цифру '2' на '1'
5. Нажмите ctrl+s
6. Импортируйте календарь
