### ISSUE TITLE
 Решение со сдвигом расписания

### ISSUE THREAD

**Issue by volodmrr** [sochka/kpiexport2#8]
Для исправления перейдите на сайт:
1. Нажмите **F12**
2. Сверху перейдите во вкладку _Sources_
3. Перейдите в папку `top/kpiexport.azurwebsites.net/app`
4. В файле `app.components.js `в строчке _66_ замените цифру `2` на `1`
Должно выглядеть так `if (course.lesson_week === '1') {`
5. Нажмите **ctrl+s**
6. Импортируйте календарь без перезагрузки страницы

**Comment by kerimovkhikmet** [comment]
Уже сделал, всё работает спасибо)))
